import { ChecklistChapter } from './types';

export const checklistData: ChecklistChapter[] = [
  // CHAPTER I
  {
    id: 'I',
    title: 'Chương I. Tổ chức và Quản lý phòng xét nghiệm',
    criteriaCount: 15,
    maxScore: 23,
    criteria: [
      { id: '1.1', name: 'PXN có quyết định thành lập (PXN có giấy phép hoạt động cấp bởi cơ quan có thẩm quyền)', evidence: 'Photo quyết định thành lập PXN (với các PXN trong bệnh viện công lập) hoặc giấy phép hoạt động (các PXN tư nhân). Trong đó cần quy định về chức năng và nhiệm vụ của PXN' },
      { id: '1.2', name: 'Có sơ đồ tổ chức thể hiện mối liên quan giữa PXN và các phòng ban liên quan trong cơ sở y tế', evidence: 'Photo sơ đồ tổ chức của bệnh viện từ phòng TCCB hoặc tổ chức hành chính.' },
      { id: '1.3', name: 'PXN có sơ đồ tổ chức thể hiện được mối quan hệ giữa các vị trí và mối quan hệ qua lại giữa các nhóm chuyên môn tại phòng xét nghiệm', evidence: 'Biểu mẫu: Sơ đồ tổ chức (mã số XN-BM 5.1.1/01).' },
      { id: '1.4', name: 'PXN có xây dựng mục tiêu chất lượng nhất quán với chính sách chất lượng', evidence: 'Trong mục 2.2. về mục tiêu chất lượng của sổ tay chất lượng (XN-STCL) và mục tiêu chất lượng từng năm (có sẵn trong bộ tài liệu).' },
      { id: '1.5', name: 'PXN có lập kế hoạch chất lượng định kỳ hằng năm để đạt các mục tiêu chất lượng', evidence: 'Biểu mẫu: Kế hoạch chất lượng và kết quả giám sát (mã số XN-BM 5.1.1/05)' },
      { id: '1.6', name: 'PXN có thực hiện kế hoạch chất lượng mà PXN đã xây dựng', evidence: 'Xem các hồ sơ liên quan theo kế hoạch chất lượng (ví dụ: hồ sơ chỉ số chất lượng)' },
      { id: '1.7', name: 'PXN có xây dựng các chỉ số chất lượng thuộc cả 3 giai đoạn của quá trình XN, phù hợp với mục tiêu chất lượng mà PXN đề ra', evidence: 'Biểu mẫu: Kế hoạch theo dõi chỉ số chất lượng (mã số: XN-BM 5.1.2/01).\nBiểu mẫu: Phiếu báo cáo chỉ số chất lượng (mã số XN-BM 5.1.2/02).\nHồ sơ kết quả thống kê theo dõi từng chỉ số.' },
      { id: '1.8', name: 'Sổ tay chất lượng có bao gồm các nội dung a) Tuyên bố chính sách chất lượng, b) Cấu trúc hệ thống QLCL, c) Thiết lập mục tiêu, d) Mô tả quá trình trao đổi thông tin, e) Đảm bảo nguồn lực, f) Các quy định liên quan, g) Mô tả vai trò và trách nhiệm, h) Quy định người có thẩm quyền xem xét, i) Dẫn chiếu đến các quy trình', evidence: 'Sổ tay chất lượng có sẵn (mã số XN-STCL)' },
      { id: '1.9', name: 'Có bằng chứng về việc phổ biến/tập huấn về sổ tay chất lượng cho tất cả nhân viên PXN và những người liên quan.', evidence: 'Biểu mẫu: Biên bản phổ biến tài liệu (mã số: XN-BM 5.4.1/03).' },
      { id: '1.10', name: 'PXN có văn bản phân công công việc cho từng nhân viên', evidence: 'Biểu mẫu: Bản mô tả công việc (mã số: XN-BM 5.3.1/03)\nSổ (lịch) phân công từng vị trí với từng nhân viên cụ thể theo từng ngày, từng tuần...' },
      { id: '1.11', name: 'PXN có tổ chức họp xem xét hệ thống QLCL do lãnh đạo hoặc người được ủy quyền chủ trì ít nhất 1 lần/năm.', evidence: 'Quy trình: Xem xét của lãnh đạo (mã số: XN-QTQL 5.1.3)\nBiểu mẫu: Chương trình xem xét của lãnh đạo (mã số: XN-BM 5.1.3/01)' },
      { id: '1.12', name: 'Nội dung họp có bao gồm: đánh giá KQ thực hiện, xem xét yêu cầu XN, đánh giá sự hài lòng KH, góp ý NV, đánh giá nội bộ/bên ngoài, nguy cơ, chỉ số chất lượng, nội kiểm/ngoại kiểm, khiếu nại, chất lượng nhà cung ứng, SKPH, cải tiến, các thay đổi và khuyến nghị.', evidence: 'Biểu mẫu: Chương trình xem xét của lãnh đạo (mã số: XN-BM 5.1.3/01)' },
      { id: '1.13', name: 'PXN có lưu lại biên bản cuộc họp xem xét với lãnh đạo đơn vị, bao gồm các phát hiện và hành động phát sinh từ cuộc họp xem xét của lãnh đạo.', evidence: 'Biểu mẫu: Biên bản xem xét của lãnh đạo (mã số: XN-BM 5.1.3/02)' },
      { id: '1.14', name: 'Các công việc phát sinh từ cuộc họp xem xét của lãnh đạo có được thực hiện theo kế hoạch đề ra', evidence: 'Hồ sơ HĐKP (XN-HS 5.10.2) và HĐPN (XN-HS 5.10.3)' },
      { id: '1.15', name: 'Việc thực hiện các công việc đề ra trong cuộc họp xem xét với lãnh đạo có được trao đổi và chia sẻ với lãnh đạo cơ quan chủ quản, nhân viên có liên quan.', evidence: 'Văn bản thông báo kết luận của lãnh đạo đơn vị về kết quả xét xét lãnh đạo của PXN. Trong đó các nội dung quan trọng được thông báo tới tất cả nhân viên PXN và các đơn vị liên quan.' },
    ],
  },
  // CHAPTER II
  {
    id: 'II',
    title: 'Chương II. Quản lý tài liệu và hồ sơ',
    criteriaCount: 8,
    maxScore: 10,
    criteria: [
        { id: '2.1', name: 'PXN có quy trình kiểm soát tài liệu bên ngoài và nội bộ gồm cả hướng dẫn biên soạn quy trình thực hành chuẩn, hướng dẫn rút gọn, các biểu mẫu', evidence: 'Quy trình kiểm soát tài liệu: Mã số XN-QTQL 5.2.1\nQuy trình hướng dẫn biên soạn quy trình thực hành chuẩn: Mã số XN-QTQL 5.2.2' },
        { id: '2.2', name: 'Tất cả các tài liệu được PXN xây dựng bao gồm các yếu tố nhận dạng sau: a) Tên, b) Mã, c) Ngày ban hành, d) Số trang, e) Chữ ký xác nhận', evidence: 'Quy trình hướng dẫn biên soạn quy trình thực hành chuẩn: Mã số XN-QTQL 5.2.2\nĐưa ra 1 bản quy trình quản lý, quy trình kỹ thuật, hướng dẫn, biểu mẫu để chuyên gia kiểm tra hình thức.' },
        { id: '2.3', name: 'Tất cả các tài liệu được bảo quản hợp lý dễ dàng truy cập', evidence: 'Có tủ lưu hồ sơ, có các kẹp hồ sơ. Các biểu mẫu trắng cần in sẵn 1 bản để người dùng tiếp cận, các quy trình có bản sao kẹp trong từng bộ hồ sơ...' },
        { id: '2.4', name: 'PXN thực hiện kiểm soát tài liệu chặt chẽ bao gồm: a) Phiếu yêu cầu, b) Hồ sơ phân phối, c) Danh mục, d) Nhận biết thay đổi, e) Rà soát định kỳ, f) Dễ đọc, g) Đánh dấu hết hiệu lực, h) Lưu trữ tài liệu hết hiệu lực', evidence: 'Biểu mẫu: Phiếu đề nghị biên soạn/sửa đổi tài liệu (mã số XN-BM 5.2.1/04)\nBiểu mẫu: Sổ theo dõi phân phối/thu hồi tài liệu (mã số XN-BM 5.2.1/03)\nBiểu mẫu: Danh mục tài liệu nội bộ (mã số XN-BM 5.2.1/01).\nBiểu mẫu: Danh mục tài liệu bên ngoài (mã số XN-BM 5.2.1/02)\nBiểu mẫu: Phiếu soát xét tài liệu định kỳ (mã số XN-BM 5.2.1/05)' },
        { id: '2.5', name: 'Các quy trình rút gọn/hướng dẫn có được kiểm soát', evidence: 'Quy trình hướng dẫn biên soạn quy trình thực hành chuẩn: Mã số XN-QTQL 5.2.2\nĐưa ra 1 bản quy trình rút gọn, hướng dẫn, để chuyên gia kiểm tra hình thức.' },
        { id: '2.6', name: 'PXN có quy trình và thực hiện nhận biết, thu thập, đánh số, truy cập, lưu trữ, bảo quản, chỉnh sửa và hủy hồ sơ an toàn', evidence: 'Quy trình quản lý hồ sơ: Mã số XN-QTQL 5.2.3.\nBiểu mẫu Danh mục hồ sơ (mã số XN-BM 5.2.3/01)' },
        { id: '2.7', name: 'PXN có quy định thời gian lưu đối với từng loại hồ sơ và phù hợp với các quy định quốc gia hoặc các quy định có liên quan', evidence: 'Biểu mẫu Danh mục hồ sơ (mã số XN-BM 5.2.3/01)' },
        { id: '2.8', name: 'PXN có nơi lưu hồ sơ phù hợp (hồ sơ bản giấy hoặc bản mềm/bản điện tử), bảo đảm hồ sơ không bị hư hại, thất lạc hoặc truy cập trái phép', evidence: 'Có các cặp còng lưu hồ sơ riêng biệt.\nCác cặp hồ sơ đặt trong các tủ hồ sơ. Tủ hồ sơ có khóa để ngăn truy cập trái phép.\nCó USB/ổ cứng di động để lưu các file backup hồ sơ điện tử (Hồ sơ kết quả XN của bệnh nhân)' },
    ],
  },
    // CHAPTER III
  {
    id: 'III',
    title: 'Chương III. Quản lý nhân sự',
    criteriaCount: 17,
    maxScore: 21,
    criteria: [
        { id: '3.1', name: 'PXN xây dựng yêu cầu về trình độ chuyên môn, bằng cấp, đào tạo, kinh nghiệm và các kỹ năng cần thiết cho từng vị trí trong PXN', evidence: 'Đề án vị trí việc làm: mã số QĐXN 01' },
        { id: '3.2', name: 'PXN có xây dựng bản mô tả công việc bao gồm trách nhiệm, quyền hạn và nhiệm vụ cho tất cả nhân viên', evidence: 'Biểu mẫu: Bản mô tả công việc (mã số XN-BM 5.3.1/03)' },
        { id: '3.3', name: 'Nhân viên PXN được đào tạo phù hợp để đảm nhận các công việc được giao', evidence: 'Biểu mẫu: Bản mô tả công việc (mã số XN-BM 5.3.1/03)\nBiểu mẫu: Phiếu đào tạo nội bộ (mã số XN-BM 5.3.2/03)\nBiểu mẫu: Kết quả đào tạo nội bộ (mã số XN-BM 5.3.2/05)\nBiểu mẫu: Lý lịch cá nhân (mã số XN-BM 5.3.1/02)\nLưu các văn bằng, chứng chỉ có liên quan đến hoạt động chuyên môn của từng nhân viên.' },
        { id: '3.4', name: 'PXN có quy trình quản lý nhân sự và lưu hồ sơ nhân sự', evidence: 'Quy trình quản lý nhân sự: Mã số XN-QTQL 5.3.1\nHồ sơ quản lý nhân sự: Mã số XN-HS 5.3.1' },
        { id: '3.5', name: 'Người được phép ký duyệt kết quả có đủ năng lực theo quy định', evidence: 'Sổ tay chất lượng: Mã số XN-STCL (nêu chính sách về ký duyệt kết quả)\nBiểu mẫu: Thẩm quyền ký (mã số XN-BM 5.1.1/02)\nBiểu mẫu: Lý lịch cá nhân (mã số XN-BM 5.3.1/02)' },
        { id: '3.6', name: 'Trưởng PXN có quyết định bổ nhiệm bằng văn bản', evidence: 'Quyết định bổ nhiệm/phân công trưởng/phụ trách phòng xét nghiệm.' },
        { id: '3.7', name: 'PXN có phân công/bổ nhiệm nhân viên QLCL và quản lý kỹ thuật với chức năng, nhiệm vụ rõ ràng', evidence: 'Quyết định bổ nhiệm/phân công nhân viên QLCL và QLKT\nĐề án vị trí việc làm mã số QĐXN 01\nBiểu mẫu: Bản mô tả công việc (mã số XN-BM 5.3.1/03)' },
        { id: '3.8', name: 'PXN có đào tạo định hướng/giới thiệu cho nhân viên mới và nội dung giới thiệu bao gồm: a) Giới thiệu về tổ chức; b) Giới thiệu về PXN; c) Các điều khoản công việc; d) Cơ sở vật chất; e) Sức khỏe và an toàn PXN;', evidence: 'Quy trình quản lý đào tạo: Mã số XN-QTQL\nBiểu mẫu: Kế hoạch giám sát và phân công giám sát nhân viên mới (mã số XN-BM 5.3.2/07)\nBiểu mẫu: Hướng dẫn nhân viên mới (mã số XN-BM 5.3.2/08 ).' },
        { id: '3.9', name: 'PXN có đánh giá nhân viên mới sau tập huấn/đào tạo', evidence: 'Biểu mẫu: Kết quả đào tạo nội bộ (mã số XN-BM 5.3.2/05)' },
        { id: '3.10', name: 'PXN có kế hoạch và thực hiện giám sát nhân viên mới sau khi được phân công nhiệm vụ trong khoảng thời gian tối thiểu 1 năm', evidence: 'Biểu mẫu: Kế hoạch giám sát và phân công giám sát nhân viên mới (mã số XN-BM 5.3.2/07)' },
        { id: '3.11', name: 'PXN có thực hiện chương trình tập huấn bắt buộc cho nhân viên, bao gồm những nội dung sau: a) Hệ thống QLCL; b) Các quá trình (luồng công việc) và các quy trình thực hiện; c) Hệ thống thông tin PXN; d) Sức khỏe và an toàn PXN; e) Bảo mật thông tin khách hàng; f) Đạo đức nghề nghiệp bao gồm tránh xung đột quyền lợi;', evidence: 'Biểu mẫu: Sổ theo dõi đào tạo nội bộ (mã số XN-BM 5.3.2/04)\nBiểu mẫu: Kết quả đào tạo nội bộ (mã số XN-BM 5.3.2/05)\nBiểu mẫu: Xem xét hiệu quả quả đào tạo nội bộ (mã số XN-BM 5.3.2/06)\nCam kết đạo đức nghề nghiệp : QĐXN 02\nBiểu mẫu: Cam kết bảo mật thông tin và đảm bảo chất lượng công việc (mã số XN-BM 5.1.1/04)' },
        { id: '3.12', name: 'PXN có quy trình đánh giá năng lực nhân viên', evidence: 'Quy trình đánh giá năng lực nhân viên : Mã số XN-QTQL 5.3.3' },
        { id: '3.13', name: 'PXN thực hiện đánh giá năng lực nhân viên định kỳ hằng năm', evidence: 'Biểu mẫu: Kế hoạch đánh giá năng lực nhân viên (mã số XN- BM 5.3.3/01)\nBiểu mẫu: Phiếu đánh giá năng lực nhân viên (mã số XN- BM 5.3.3/02)\nBiểu mẫu: Xem xét năng lực nhân viên (mã số XN- BM 5.3.3/03)' },
        { id: '3.14', name: 'PXN có đánh giá kết quả công tác của nhân viên theo định kỳ', evidence: 'Lưu bản sao đánh giá công chức/viên chức hàng năm của đơn vị.' },
        { id: '3.15', name: 'PXN có xây dựng kế hoạch đào tạo liên tục cho từng nhân viên', evidence: 'Biểu mẫu: Phiếu yêu cầu đào tạo cá nhân (mã số XN-BM 5.3.2/01)\nBiểu mẫu: Kế hoạch đào tạo (mã số XN-BM 5.3.2/02)' },
        { id: '3.16', name: 'Nhân viên PXN có tham gia vào các chương trình đào tạo liên tục theo quy định', evidence: 'Đào tạo bên ngoài: Lưu giữ các kết quả đào tạo liên tục như giấy chứng nhận, chứng chỉ...\nĐào tạo nội bộ:\n+ Biểu mẫu: Sổ theo dõi đào tạo nội bộ (mã số XN-BM 5.3.2/04)\n+ Biểu mẫu: Kết quả đào tạo nội bộ (mã số XN-BM 5.3.2/05)' },
        { id: '3.17', name: 'PXN có lưu hồ sơ nhân sự của tất cả nhân viên, bao gồm những nội dung sau: a) Bản sao chứng chỉ hoặc bằng cấp; b) Lý lịch khoa học; c) Bản mô tả công việc; d) Định hướng nhân viên mới (nếu có); e) Phiếu theo dõi quá trình đào tạo, tập huấn; f) Kết quả đánh giá năng lực nhân viên; g) Báo cáo tai nạn và các phơi nhiễm trong khi hành nghề; h) Phiếu khám sức khỏe và hồ sơ tiêm chủng phòng ngừa tác nhân gây bệnh có liên quan nhiệm vụ được giao.', evidence: 'Hồ sơ nhân sự của từng cá nhân: Mã số XN-HS 5.3.1. Hồ sơ bao gồm: + Bản sao chứng chỉ hoặc bằng cấp; + Lý lịch cá nhân (mã số XN-BM 5.3.1/02); + Bản mô tả công việc (mã số XN-BM 5.3.1/03); + Bảng phân công định hướng cho nhân viên mới (mã số XN-BM 5.3.1/06); + Phiếu yêu cầu đào tạo cá nhân (mã số XN-BM 5.3.2/01); + Phiếu đánh giá năng lực nhân viên (mã số XN- BM 5.3.3/02); + Phiếu báo cáo sự cố (mã số XN- BM 5.12.1/07); + Phiếu tiêm chủng (mã số XN-BM 5.3.1/04); + Phiếu kê khai khám sức khỏe (mã số XN-BM 5.3.1/05).' },
    ],
  },
  // CHAPTER IV
  {
    id: 'IV',
    title: 'Chương IV. Cung cấp dịch vụ và Quản lý khách hàng',
    criteriaCount: 10,
    maxScore: 13,
    criteria: [
        { id: '4.1', name: 'PXN có quy trình khảo sát sự hài lòng khách hàng', evidence: 'Quy trình khảo sát sự hài lòng của khách hàng: Mã số XN-QTQL 5.4.3' },
        { id: '4.2', name: 'PXN có quy trình quản lý khiếu nại hoặc phản hồi của khách hàng, các bên liên quan và nhân viên', evidence: 'Quy trình giải quyết khiếu nại: Mã số XN-QTQL 5.4.2' },
        { id: '4.3', name: 'PXN có công cụ đánh giá định kỳ mức độ hài lòng khách hàng', evidence: 'Biểu mẫu: Phiếu thu thập ý kiến khách hàng (mã số XN-BM 5.4.3/02)' },
        { id: '4.4', name: 'PXN có hồ sơ khảo sát ý kiến khách hàng', evidence: 'Biểu mẫu: Kế hoạch khảo sát sự không hài lòng (mã số XN-BM 5.4.3/01)\n- Biểu mẫu: Phiếu thu thập ý kiến khách hàng (mã số XN-BM 5.4.3/02)\n- Biểu mẫu: Báo cáo tổng hợp đánh giá của khách hàng (mã số XN-BM 5.4.3/03)' },
        { id: '4.5', name: 'PXN có đánh giá thỏa thuận sử dụng dịch vụ với PXN chuyển gửi như xem xét khả năng cung ứng dịch vụ có đáp ứng các yêu cầu chất lượng.', evidence: 'Quy trình phòng xét nghiệm tham chiếu: Mã số XN-QTQL 5.4.4' },
        { id: '4.6', name: 'PXN có hồ sơ xem xét và giải quyết các khiếu nại/ phản hồi khách hàng', evidence: 'Biểu mẫu: Sổ theo dõi khiếu nại (mã số XN-BM 5.4.2/01)\nBiểu mẫu: Biên bản giải quyết khiếu nại (mã số XN-BM 5.4.2/02)' },
        { id: '4.7', name: 'PXN có lưu hồ sơ khiếu nại và HĐKP', evidence: 'Biểu mẫu: Sổ theo dõi khiếu nại (mã số XN-BM 5.4.2/01)\nBiểu mẫu: Biên bản giải quyết khiếu nại (mã số XN-BM 5.4.2/02)\nBiểu mẫu: Sổ theo dõi hành động khắc phục (mã số XN-BM 5.10.2/01)\n- Biểu mẫu: Phiếu báo cáo hành động khắc phục (mã số XN-BM 5.10.2/02)' },
        { id: '4.8', name: 'Sổ tay dịch vụ khách hàng/ Sổ tay lấy mẫu được ban hành và phân phối cho các khoa có liên quan', evidence: 'Sổ tay dịch vụ khách hàng: Mã số XN-STDV\n- Biểu mẫu: Sổ theo dõi phân phối/thu hồi tài liệu (mã số XN-BM 5.2.1/03)' },
        { id: '4.9', name: 'Bản sao sổ tay dịch vụ khách hàng/ Sổ tay lấy mẫu sẵn để nhân viên PXN tiếp cận được dễ dàng', evidence: 'Biểu mẫu: Biên bản phổ biến tài liệu (mã số XN-BM 5.4.1/03)\nCác bản sao của STDVKH được đặt ở các phòng để nhân viên tiện sử dụng.' },
        { id: '4.10', name: 'PXN có sẵn các thông tin cần thiết cho khách hàng, bao gồm: a) Vị trí, b) Các loại DV, c) Lịch làm việc, d) Các XN, e) Hướng dẫn điền phiếu, f) Hướng dẫn chuẩn bị NB, g) Hướng dẫn thu thập mẫu, h) Hướng dẫn vận chuyển mẫu, i) Yêu cầu bảo mật, j) Tiêu chuẩn chấp nhận/từ chối, k) Yếu tố ảnh hưởng, l) Tư vấn lâm sàng, m) Chính sách bảo mật, n) Hướng dẫn khiếu nại.', evidence: 'Xem xét nội dung của sổ tay DVKH (mã số XN-STDV) có các nội dung theo yêu cầu.\nSổ tay giá trị tham chiếu: Mã số XN-STTC.\nSổ tay giá trị báo động: Mã số XN-STBĐ.' },
    ],
  },
    // CHAPTER V
  {
    id: 'V',
    title: 'Chương V. Quản lý trang thiết bị',
    criteriaCount: 19,
    maxScore: 30,
    criteria: [
        { id: '5.1', name: 'PXN có quy trình quản lý TTB', evidence: 'Quy trình quản lý thiết bị: Mã số XN-QTQL 5.5.1' },
        { id: '5.2', name: 'PXN được trang bị đủ thiết bị phù hợp với yêu cầu công việc, danh mục kỹ thuật', evidence: 'Biểu mẫu: Danh mục trang thiết bị (mã số XN-BM 5.5.1/01)' },
        { id: '5.3', name: 'PXN có kiểm tra TTB mới nhận về và bảo đảm TTB hoạt động tốt trước khi đưa vào sử dụng', evidence: 'Biểu mẫu: Biên bản bàn giao thiết bị (mã số XN-BM 5.5.1/02).\nKết quả nội kiểm khi tiếp nhận thiết bị.' },
        { id: '5.4', name: 'Có hướng dẫn sử dụng TTB bằng tiếng Việt', evidence: 'PXN xây dựng hướng dẫn sử dụng (hoặc quy trình vận hành) dựa trên hướng dẫn của hãng.' },
        { id: '5.5', name: 'Hướng dẫn sử dụng từng TTB được đặt tại nơi dễ tiếp cận, sử dụng', evidence: 'Hướng dẫn dài (quy trình dài để trong hồ sơ thiết bị).\nHướng dẫn ngắn dán gần thiết bị.' },
        { id: '5.6', name: 'Toàn bộ TTB PXN được dán nhãn nhận biết duy nhất', evidence: 'Dán nhãn cho từng thiết bị theo mẫu trong quy trình quản lý thiết bị.' },
        { id: '5.7', name: 'Nhân viên được giao vận hành TTB được đào tạo phù hợp', evidence: 'Chứng nhận/chứng chỉ đào tạo vận hành thiết bị của hãng.\nBiểu mẫu: Phiếu đào tạo nội bộ (mã số XN-BM 5.3.2/03) cho các nhân viên không có chứng nhận từ hãng.' },
        { id: '5.8', name: 'PXN có danh sách và thông tin liên hệ của đơn vị cung cấp và bảo hành TTB', evidence: 'Biểu mẫu: Danh sách nhà cung cấp thiết bị (mã số XN-BM 5.5.1/09).' },
        { id: '5.9', name: 'PXN có sổ nhật ký sử dụng cho từng TTB', evidence: 'Biểu mẫu: Nhật ký sử dụng thiết bị (mã số XN-BM 5.5.1/05).' },
        { id: '5.10', name: 'Trong QTQL TTB đề cập đến nội dung xử lý tránh lây nhiễm chéo và hư hỏng khi vận chuyển, bảo quản và sử dụng TTB', evidence: 'Mục 5.6 trong Quy trình quản lý thiết bị: Mã số XN-QTQL 5.5.1.' },
        { id: '5.11', name: 'PXN có kế hoạch và thực hiện kiểm định/ hiệu chuẩn theo quy định của pháp luật/ của nhà sản xuất đối với các TTB có thể gây ảnh hưởng tới kết quả xét nghiệm', evidence: 'Biểu mẫu: Kế hoạch hiệu chuẩn và bảo dưỡng thiết bị (mã số XN-BM 5.5.1/06).\nBiểu mẫu: Đánh giá kết quả hiệu chuẩn (mã số XN-BM 5.5.1/07).' },
        { id: '5.12', name: 'PXN có thực hiện bảo trì, bảo dưỡng TTB theo hướng dẫn của nhà sản xuất', evidence: 'Biểu mẫu: Phiếu bảo trì, bảo dưỡng thiết bị (mã số XN-BM 5.5.1/08).' },
        { id: '5.13', name: 'PXN có thực hiện khử nhiễm TTB trước khi sửa chữa, thanh lý', evidence: 'Biểu mẫu: Phiếu theo dõi khử nhiễm trang thiết bị (mã số XN-BM 5.5.1/11).' },
        { id: '5.14', name: 'Các TTB hỏng/hoặc chờ thanh lý được dán nhãn nhận biết/phân biệt với TTB khác', evidence: 'Dán nhãn cho thiết bị hỏng/không sử dụng theo mẫu trong quy trình quản lý thiết bị.' },
        { id: '5.15', name: 'QTQLTTB đề cập tới các sự cố nghiêm trọng và tai nạn liên quan tới việc sử dụng TTB được thông báo tới nhà sản xuất hoặc phân phối, cơ quan quản lý có thẩm quyền và có lưu hồ sơ', evidence: 'Mục 5.4 trong Quy trình quản lý thiết bị: Mã số XN-QTQL 5.5.1.\n- Biểu mẫu: Phiếu theo báo cáo sự cố (mã số XN-BM 5.12.1/07).' },
        { id: '5.16', name: 'PXN kiểm tra và ghi lại tình trạng TTB mới đưa vào sử dụng hoặc sau sửa chữa', evidence: 'Biểu mẫu: Nhật ký sử dụng thiết bị (mã số XN-BM 5.5.1/05).\nBiểu mẫu: Lý lịch thiết bị (mã số XN-BM 5.5.1/03).' },
        { id: '5.17', name: 'PXN có quy trình dự phòng trong trường hợp hư hỏng TTB', evidence: 'Mục 5.4 trong Quy trình quản lý thiết bị: Mã số XN-QTQL 5.5.1.' },
        { id: '5.18', name: 'PXN cung cấp dịch vụ xét nghiệm liên tục, không bị gián đoạn do hư hỏng TTB trong suốt năm vừa qua (hoặc từ lần đánh giá gần nhất)', evidence: 'Biểu mẫu: Biên bản gửi thiết bị sửa chữa – hiệu chuẩn (mã số XN-BM 5.5.1/10).\nBiểu mẫu: Phiếu theo báo cáo sự cố (mã số XN-BM 5.12.1/07).' },
        { id: '5.19', name: 'PXN có lưu giữ đầy đủ hồ sơ liên quan tới thiết bị, bao gồm: a) Nhận dạng, b) Tên NSX, c) Thông tin liên hệ, d) Ngày nhận và sử dụng, e) Vị trí, f) Điều kiện, g) Hướng dẫn sử dụng, h) Hồ sơ xác nhận, i) Hồ sơ kiểm định/hiệu chuẩn/bảo trì, j) Hỏng hóc, sự cố', evidence: 'Hồ sơ quản lý thiết bị: Mã số XN-HS 5.5.1.\nHồ sơ của mỗi thiết bị cần có: Lý lịch thiết bị, Biên bản bàn giao, Nhật ký sử dụng, Kế hoạch và kết quả hiệu chuẩn/bảo trì, Phiếu khử nhiễm, Hướng dẫn, Kết quả nội/ngoại kiểm, Quy trình vận hành, Phiếu báo cáo sự cố, Biên bản gửi sửa chữa, Giấy chứng nhận CO, CQ.' },
    ],
  },
    // CHAPTER VI
  {
    id: 'VI',
    title: 'Chương VI. Đánh giá nội bộ',
    criteriaCount: 9,
    maxScore: 13,
    criteria: [
        { id: '6.1', name: 'PXN có quy trình và kế hoạch đánh giá nội bộ.', evidence: 'Quy trình đánh giá nội bộ: Mã số XN-QTQL 5.6.1\nBiểu mẫu: Kế hoạch đánh giá nội bộ (mã số XN-BM 5.6.1/01).' },
        { id: '6.2', name: 'Chương trình đánh giá xác định tiêu chí, phạm vi, tần suất và phương pháp thực hiện', evidence: 'Biểu mẫu: Chương trình đánh giá nội bộ (mã số XN-BM 5.6.1/03).' },
        { id: '6.3', name: 'PXN tiến hành đánh giá nội bộ theo kế hoạch đề ra', evidence: 'Biểu mẫu: Báo cáo phát hiện trong đánh giá nội bộ (mã số XN-BM 5.6.1/04).\nBiểu mẫu: Báo cáo kết quả đánh giá nội bộ (mã số XN-BM 5.6.1/05).' },
        { id: '6.4', name: 'Đánh giá nội bộ được thực hiện do nhân viên đã được đào tạo về QLCL và bảo đảm khách quan nhân viên không tham gia đánh giá các hoạt động mà họ đang thực hiện', evidence: 'Biểu mẫu: Phiếu đề nghị thành lập đoàn đánh giá (mã số XN-BM 5.6.1/02).\nBiểu mẫu: Chương trình đánh giá nội bộ (mã số XN-BM 5.6.1/03).' },
        { id: '6.5', name: 'Đánh giá nội bộ xem xét và đánh giá tất cả các hoạt động của hệ thống QLCL', evidence: 'Biểu mẫu: Chương trình đánh giá nội bộ (mã số XN-BM 5.6.1/03).\nBiểu mẫu: Báo cáo phát hiện trong đánh giá nội bộ (mã số XN-BM 5.6.1/04).' },
        { id: '6.6', name: 'PXN có lưu hồ sơ kết quả đánh giá nội bộ', evidence: 'Biểu mẫu: Báo cáo phát hiện trong đánh giá nội bộ (mã số XN-BM 5.6.1/04).\nBiểu mẫu: Báo cáo kết quả đánh giá nội bộ (mã số XN-BM 5.6.1/05).\n- Biểu mẫu: Báo cáo kết quả đánh giá nội bộ (mã số XN-BM 5.6.1/05).' },
        { id: '6.7', name: 'Kết quả đánh giá nội được báo cáo với trưởng/phụ trách PXN/lãnh đạo cơ sở y tế', evidence: 'Biểu mẫu: Chương trình xem xét của lãnh đạo (mã số XN-BM 5.1.3/01).\nBiểu mẫu: Biên bản xem xét của lãnh đạo (mã số XN-BM 5.1.3/02).' },
        { id: '6.8', name: 'Khuyến cáo về HĐKP và HĐPN được nêu ra dựa trên kết quả đánh giá nội bộ', evidence: 'Biểu mẫu: Báo cáo kết quả đánh giá nội bộ (mã số XN-BM 5.6.1/05).' },
        { id: '6.9', name: 'Kế hoạch thực hiện HĐKP và HĐPN được thực hiện theo thời gian đề ra và được lưu hồ sơ', evidence: 'Biểu mẫu: Phiếu báo cáo hành động khắc phục (mã số XN-BM 5.10.2/02).\nBiểu mẫu: Phiếu báo cáo hành động phòng ngừa (mã số XN-BM 5.10.3/02).' },
    ],
  },
  {
    id: 'VII',
    title: 'Chương VII. Quản lý mua sắm vật tư, hóa chất và sinh phẩm',
    criteriaCount: 17,
    maxScore: 23,
    criteria: [
      { id: '7.1', name: 'PXN có áp dụng quy trình lựa chọn mua sắm TTB, vật tư, hóa chất và sinh phẩm', evidence: 'Quy trình dịch vụ và vật tư bên ngoài: Mã số XN-QTQL 5.7.1' },
      { id: '7.2', name: 'PXN có kế hoạch nhu cầu TTB, vật tư, hóa chất và sinh phẩm hàng năm', evidence: 'Biểu mẫu: Phiếu đề nghị mua sắm và dịch vụ (mã số XN-BM 5.7.1/01).' },
      { id: '7.3', name: 'PXN có tham gia vào quá trình xây dựng nhu cầu, lựa chọn nhà thầu, nghiệm thu TTB, vật tư, hóa chất và sinh phẩm', evidence: 'Biểu mẫu: Phiếu đề nghị mua sắm và dịch vụ (mã số XN-BM 5.7.1/01).\n- Biểu mẫu: Phiếu đề xuất yêu cầu chất lượng hàng hóa – dịch vụ (mã số XN-BM 5.7.1/02).\nBiên bản họp thầu mua sắm (theo BV hoặc sở y tế)' },
      { id: '7.4', name: 'PXN có cập nhật danh sách các nhà cung ứng TTB, vật tư, hóa chất và sinh phẩm đã được duyệt', evidence: 'Biểu mẫu: Danh sách nhà cung cấp được lựa chọn (mã số XN-BM 5.7.1/03).' },
      { id: '7.5', name: 'PXN có đánh giá chất lượng của nhà cung ứng', evidence: 'Biểu mẫu: Phiếu đánh giá nhà cung cấp (mã số XN-BM 5.7.1/04).' },
      { id: '7.6', name: 'PXN có quy trình tiếp nhận, bảo quản, kiểm tra và lưu kho sinh phẩm và vật tư', evidence: 'Quy trình quản lý vật tư: Mã số XN-QTQL 5.7.2' },
      { id: '7.7', name: 'Khu vực lưu trữ, bảo quản hóa chất, sinh phẩm và vật tư tiêu hao có đủ không gian và đảm bảo các yêu cầu sau: a) Sắp xếp ngăn nắp; b) Không có bụi bẩn, chuột và côn trùng; c) Phân chia vị trí và ghi nhãn cho từng loại vật tư đã được kiểm kê; d) Khu vực bảo quản tránh được ánh nắng trực tiếp và bảo đảm thông gió; e) Nhiệt độ và độ ẩm tại khu vực bảo quản được theo dõi hằng ngày; f) Việc ra vào kho/nơi lưu trữ được kiểm soát.', evidence: 'Biểu mẫu: Danh mục vật tư (mã số XN-BM 5.7.2/01).\nBiểu mẫu: Phiếu theo dõi vật tư (mã số XN-BM 5.7.2/04).\nBiểu mẫu: Phiếu theo dõi điều kiện môi trường (mã số XN-BM 5.12.1/03).\nBiểu mẫu: Nhật ký ra vào khu vực xét nghiệm (mã số XN-BM 5.12.1/02).' },
      { id: '7.8', name: 'Nếu PXN không thực hiện lưu trữ hóa chất, sinh phẩm và vật tư tại PXN, thì PXN có thực hiện kiểm tra không gian và điều kiện nơi bảo quản', evidence: 'Biểu mẫu: Phiếu theo dõi điều kiện môi trường (mã số XN-BM 5.12.1/03).' },
      { id: '7.9', name: 'Đối với mỗi loại kít xét nghiệm hoặc lô hóa chất sinh, phẩm mới nhận, PXN đánh giá chất lượng trước khi sử dụng', evidence: 'Biểu mẫu: Kiểm tra chất lượng vật tư (mã số XN-BM 5.7.2/04).' },
      { id: '7.10', name: 'Các hóa chất, sinh phẩm, vật tư hết hạn hoặc không đạt chất lượng được dán nhãn cảnh báo và lưu trữ riêng', evidence: 'Dán nhãn đỏ cảnh báo' },
      { id: '7.11', name: 'Hóa chất, sinh phẩm độc hại được lưu trữ đúng quy định', evidence: 'Danh mục nhãn nhận biết hóa chất độc hại trong sổ tay an toàn. (mã số XN-STAT)' },
      { id: '7.12', name: 'PXN có các hướng dẫn sử dụng hóa chất, sinh phẩm và vật tư tiêu hao, bao gồm các hướng dẫn của nhà sản xuất, các nguyên tắc và xử lý an toàn', evidence: 'Hướng dẫn sử dụng từng loại hóa chất PXN xây dựng theo hướng dẫn của NSX.' },
      { id: '7.13', name: 'PXN thực hiện Quy tắc FEFO ("First Expire/First Out", nghĩa là vật tư hóa chất và sinh phẩm hết hạn sử dụng trước phải được dùng trước)', evidence: 'Vật tư, Hóa chất và sinh phẩm còn hạn dài thì đeo thẻ màu xanh, gần hết hạn đeo thẻ màu vàng, hết hạn đeo thẻ màu đỏ... Trong kho lưu trữ cần sắp xếp sao cho hóa chất, sinh phẩm gần hết hạn ra phía ngoài, các hóa chất còn hạn dài xếp phía trong.' },
      { id: '7.14', name: 'PXN có lưu các hồ sơ liên quan đến vật tư, hóa chất và sinh phẩm: a) Nhận dạng hóa chất, sinh phẩm hoặc VTTH; b) Tên của nhà sản xuất và mã số lô /đợt sản xuất; c) Thông tin liên lạc của nhà phân phối/cung cấp hoặc nhà sản xuất; d) Ngày nhận, ngày hết hạn, ngày đưa vào sử dụng, ngày ngừng sử dụng (nếu có); e) Tình trạng khi nhận (ví dụ: có thể chấp nhận hoặc bị hư hại); f) Chất lượng sinh phẩm, hóa chất và VTTH trước khi sử dụng; g) Giám sát số lượng hóa chất, sinh phẩm và VTTH (Số ghi chép việc sử dụng sinh phẩm/thẻ kho).', evidence: 'Biểu mẫu: Danh mục vật tư (mã số XN-BM 5.7.2/01).\nBiểu mẫu: Biên bản bàn giao vật tư (mã số XN-BM 5.7.2/02).\nBiểu mẫu: Kiểm tra chất lượng vật tư (mã số XN-BM 5.7.2/03).\n- Biểu mẫu: Phiếu theo dõi vật tư (mã số XN-BM 5.7.2/04).\nBiểu mẫu: Danh sách nhà cung cấp được lựa chọn (mã số XN-BM 5.7.1/03).' },
      { id: '7.15', name: 'Với những hóa chất, sinh phẩm/ môi trường do PXN tự chuẩn bị, ngoài các thông tin trên, PXN lưu giữ thông tin người chuẩn bị và hạn sử dụng nồng độ (nếu có).', evidence: 'Biểu mẫu: Sổ pha chế hóa chất (mã số XN-BM 5.7.2/06).' },
      { id: '7.16', name: 'Xử lý đúng quy định các hóa chất, sinh phẩm, vật tư hết hạn hoặc không đạt tiêu chuẩn', evidence: 'Biểu mẫu: Biên bản hủy vật tư (mã số XN-BM 5.7.2/05).' },
      { id: '7.17', name: 'Trong năm vừa qua hoặc từ lần đánh giá gần nhất, PXN không bị gián đoạn dịch vụ XN do nguyên nhân liên quan đến hóa chất, sinh phẩm vật tư', evidence: 'Biểu mẫu: Phiếu theo dõi vật tư (mã số XN-BM 5.7.2/04).' },
    ]
  },
  {
    id: 'VIII',
    title: 'Chương VIII. Quản lý quá trình xét nghiệm',
    criteriaCount: 27,
    maxScore: 57,
    criteria: [
        { id: '8.1', name: 'Các mẫu XN được gửi cùng phiếu yêu cầu XN', evidence: 'Quy trình trước xét nghiệm: Mã số XN-QTQL 5.8.1\nTùy theo cách quản lý của từng bệnh viện, các phiếu này có thể ở dạng điện tử hoặc phiếu in sẵn.' },
        { id: '8.2', name: 'Phiếu yêu cầu xét nghiệm có đầy đủ các thông tin sau không: a) Thông tin xác định người bệnh; b) Loại mẫu ban đầu; c) Các xét nghiệm yêu cầu; d) Chẩn đoán lâm sàng của người bệnh; e) Ngày và giờ lấy mẫu bệnh phẩm; tên nhân viên lấy mẫu; f) Ngày và giờ PXN nhận mẫu, họ và tên nhân viên nhận mẫu; g) Tên và chữ ký của bác sĩ chỉ định xét nghiệm.', evidence: 'Trên phiếu chỉ định xét nghiệm cần thể hiện đầy đủ các thông tin theo yêu cầu.' },
        { id: '8.3', name: 'PXN có quy trình nhận mẫu, bao gồm nội dung sau: a) Xác định thông tin của người bệnh trên mẫu bệnh phẩm; b) Mẫu XN được đánh giá chất lượng theo tiêu chí chấp nhận hay loại bỏ mẫu; c) Có hồ sơ tiếp nhận mẫu, ghi rõ thời gian và người nhận; d) Khi mẫu XN ban đầu được chia nhỏ, PXN có phương pháp để xác định nhận diện mẫu của người bệnh từ mẫu XN ban đầu; e) Nếu PXN không trực 24/24h, PXN có cách thức nhận và xử lý mẫu XN ngoài giờ làm việc; f) Mẫu XN được chuyển đến đúng bộ phận xét nghiệm trong khoảng thời gian đã quy định; g) Mẫu bệnh phẩm được thu thập, vận chuyển và bảo quản theo quy định.', evidence: 'Quy trình trước xét nghiệm: Mã số XN-QTQL 5.8.1\nBiểu mẫu: Sổ giao nhận bệnh phẩm (mã số XN-BM 5.8.1/01).\nBiểu mẫu: Biên bản từ chối mẫu (mã số XN-BM 5.8.1/02).\n- Biểu mẫu: Sổ giao theo dõi mẫu không đạt (mã số XN-BM 5.8.1/03).' },
        { id: '8.4', name: 'PXN xây dựng và thực hiện các quy trình xét nghiệm cho các XN đang thực hiện tại PXN, các quy trình XN bao gồm những nội dung sau: a) Mục đích; b) Phạm vi áp dụng; c) Trách nhiệm thực hiện; d) Định nghĩa, thuật ngữ và chữ viết tắt; e) Nguyên lý/nguyên tắc; f) Trang thiết bị, nguyên vật liệu và vật tư; g) Kiểm tra chất lượng; h) An toàn; i) Nội dung thực hiện; j) Diễn giải và báo cáo kết quả; k) Lưu ý cảnh báo; l) Lưu trữ hồ sơ; m) Tài liệu liên quan; n) Tài liệu tham khảo', evidence: 'Tham khảo các mẫu quy trình xét nghiệm cho từng xét nghiệm cụ thể trong bộ tài liệu' },
        { id: '8.5', name: 'PXN xây dựng và thực hiện quy trình kiểm soát chất lượng', evidence: 'Quy trình đảm bảo chất lượng kết quả xét nghiệm: Mã số XN-QTQL 5.8.3' },
        { id: '8.6', name: 'PXN xây dựng quy định tạm dừng trả kết quả cho khách hàng nếu kết quả nội kiểm không đạt', evidence: 'Quy trình tạm dừng trả kết quả xét nghiệm: Mã số XN-QTQL 5.8.7\nBiểu mẫu: Phiếu theo dõi tạm dừng trả kết quả (mã số XN-BM 5.8.7/01).' },
        { id: '8.7', name: 'PXN thực hiện nội kiểm ở 2 mức giá trị khác nhau cho các XN định lượng;', evidence: 'Quy trình nội kiểm tra xét nghiệm định lượng: Mã số XN-QTQL 5.8.4\n- Biểu mẫu: Phiếu kết quả nội kiểm định lượng (mã số XN-BM 5.8.4/01).\n- Biểu mẫu: Biểu đồ Levey-Jennings (mã số XN-BM 5.8.4/02).\nBiểu mẫu: Phiếu đánh giá xem xét kết quả nội kiểm định kỳ (mã số XN-BM 5.8.4/03).\nBiểu mẫu: Thiết lập giới hạn kiểm soát mới (mã số XN-BM 5.8.4/04).\n- Biểu mẫu: Phiếu theo dõi sự cố nội kiểm (mã số XN-BM 5.8.4/05).\nBiểu mẫu: Phiếu theo dõi lịch chuẩn xét nghiệm (mã số XN-BM 5.8.4/06).' },
        { id: '8.8', name: 'Thực hiện nội kiểm chứng âm, chứng dương đối với các xét nghiệm định tính', evidence: 'Quy trình nội kiểm tra xét nghiệm định tính và bán định lượng: Mã số XN-QTQL 5.8.5\n- Biểu mẫu: Phiếu kết quả nội kiểm định tính (mã số XN-BM 5.8.5/01).\n- Biểu mẫu: Phiếu theo dõi sự cố nội kiểm định tính và bán định lượng (mã số XN-BM 5.8.5/03).' },
        { id: '8.9', name: 'Với xét nghiệm bán định lượng thực hiện mẫu nội kiểm trong bộ kít kèm theo hoặc vật liệu nội kiểm khác', evidence: 'Quy trình nội kiểm tra xét nghiệm định tính và bán định lượng: Mã số XN-QTQL 5.8.5\nBiểu mẫu: Phiếu kết quả nội kiểm bán định lượng (mã số XN-BM 5.8.5/02).\nBiểu mẫu: Phiếu theo dõi sự cố nội kiểm định tính và bán định lượng (mã số XN-BM 5.8.5/03).' },
        { id: '8.10', name: 'Với xét nghiệm sử dụng test nhanh cần thực hiện nội kiểm định kỳ trên mẫu nội kiểm khác bao gồm cả chứng âm và chứng dương (nếu có)', evidence: 'Quy trình nội kiểm tra xét nghiệm định tính và bán định lượng: Mã số XN-QTQL 5.8.5\nBiểu mẫu: Phiếu kết quả nội kiểm định tính (mã số XN-BM 5.8.5/01).\nBiểu mẫu: Phiếu theo dõi sự cố nội kiểm định tính và bán định lượng (mã số XN-BM 5.8.5/03).' },
        { id: '8.11', name: 'Thực hiện nội kiểm đồng thời hoặc trước khi tiến hành xét nghiệm trên mẫu người bệnh', evidence: 'Biểu mẫu: Phiếu kết quả nội kiểm định lượng (mã số XN-BM 5.8.4/01).\nBiểu mẫu: Phiếu kết quả nội kiểm định tính (mã số XN-BM 5.8.5/01).\nBiểu mẫu: Phiếu kết quả nội kiểm bán định lượng (mã số XN-BM 5.8.5/02).' },
        { id: '8.12', name: 'Khi kết quả nội kiểm không đạt, PXN tìm kiếm nguyên nhân và khắc phục, chi thực hiện tiếp XN sau khi đã hoàn thành việc khắc phục', evidence: 'Biểu mẫu: Phiếu theo dõi sự cố nội kiểm (mã số XN-BM 5.8.4/05).\nBiểu mẫu: Phiếu theo dõi sự cố nội kiểm định tính và bán định lượng (mã số XN-BM 5.8.5/03).' },
        { id: '8.13', name: 'Kết quả nội kiểm được xem xét định kỳ nhằm phát hiện và khắc phục những xu hướng ảnh hưởng tới kết quả XN', evidence: 'Biểu mẫu: Phiếu đánh giá xem xét kết quả nội kiểm định kỳ (mã số XN-BM 5.8.4/03).' },
        { id: '8.14', name: 'PXN xây dựng hướng dẫn thực hiện ngoại kiểm hoặc so sánh liên phòng', evidence: 'Quy trình ngoại kiểm tra xét nghiệm: Mã số XN-QTQL 5.8.6' },
        { id: '8.15', name: 'PXN có tham gia vào chương trình ngoại kiểm (EQA) hoặc so sánh liên phòng (đặc biệt với các xét nghiệm chưa có mẫu EQA), nếu có thì: a) Mẫu EQA được cung cấp bởi các tổ chức đã được công nhận hoặc được phép cung cấp; b) Mẫu EQA được nhân viên PXN thường làm loại XN đó thực hiện; c) Toàn bộ kết quả EQA được xem xét và được khắc phục khi có SKPH; d) Kết quả EQA được trao đổi với nhân viên có liên quan.', evidence: 'Hợp đồng đăng ký tham gia ngoại kiểm.\nBáo cáo kết quả ngoại kiểm từ đơn vị ngoại kiểm.\nBiểu mẫu: Phiếu theo dõi kết quả ngoại kiểm (mã số XN-BM 5.8.6/01).\nBiểu mẫu: Biên bản họp xem xét kết quả ngoại kiểm (mã số XN-BM 5.8.6/02).\nBiểu mẫu: Lịch phân công thực hiện mẫu ngoại kiểm (mã số XN-BM 5.8.6/03).' },
        { id: '8.16', name: 'PXN có quy định bằng văn bản, thực hiện, và lưu hồ sơ về xác nhận giá trị sử dụng/thẩm định phương pháp xét nghiệm trước khi đưa TTB hoặc sinh phẩm mới vào sử dụng.', evidence: 'Quy trình lựa chọn và phê duyệt phương pháp xét nghiệm: Mã số XN-QTQL 5.8.2\nHướng dẫn phê duyệt phương pháp xét nghiệm: Mã số HDCV 5.8.2/01\nBiểu mẫu: Phiếu đánh giá điều kiện cơ bản (mã số XN-BM 5.8.2/01).\nBiểu mẫu: Kế hoạch thử nghiệm và phê duyệt phương pháp xét nghiệm (mã số XN-BM 5.8.2/02).\nBiểu mẫu: Phiếu đánh giá độ lặp lại và tái lặp (mã số XN-BM 5.8.2/01).\nBiểu mẫu: Phiếu đánh giá độ đúng (mã số XN-BM 5.8.2/01).\nBiểu mẫu: Phiếu xác nhận khoảng tuyến tính (mã số XN-BM 5.8.2/01).\nBiểu mẫu: Phiếu xác nhận LOD, LOQ (mã số XN-BM 5.8.2/01).\nBiểu mẫu: Phiếu xác nhận khoảng tham chiếu (mã số XN-BM 5.8.2/01).\nBiểu mẫu: Phiếu báo cáo độ không đảm bảo đo (mã số XN-BM 5.8.2/01).\nBiểu mẫu: Phiếu tổng hợp kết quả và phê duyệt phương pháp xét nghiệm (mã số XN-BM 5.8.2/01).' },
        { id: '8.17', name: 'PXN tuân thủ đúng các quy trình xét nghiệm đã xây dựng.', evidence: 'Quy trình xét nghiệm được đặt ở vị trí dễ tiếp cận\nCó các hướng dẫn nhanh đặt tại vị trí XN' },
        { id: '8.18', name: 'PXN có quy trình rà soát kết quả XN trước khi trả cho khách hàng (nêu rõ người có thẩm quyền xem xét, các yếu tố cần xem xét bao gồm cả kết quả nội kiểm, ngoại kiểm, thông tin lâm sàng và các kết quả XN trước đó nếu có)', evidence: 'Quy trình Rà soát kết quả xét nghiệm: Mã số XN-QTQL 5.8.8' },
        { id: '8.19', name: 'PXN có quy định để bảo đảm báo cáo kết quả và việc sao chép là chính xác, rõ ràng', evidence: 'Quy trình trả kết quả xét nghiệm: Mã số XN-QTQL 5.8.10' },
        { id: '8.20', name: 'PXN thực hiện quy định về định dạng phiếu trả lời kết quả và hình thức trả kết quả', evidence: 'Quy trình trả kết quả xét nghiệm: Mã số XN-QTQL 5.8.10' },
        { id: '8.21', name: 'Phiếu trả kết quả có bao gồm các nội dung sau: a) Loại xét nghiệm; b) Thông tin PXN; c) Nhận dạng XN chuyển gửi; d) Thông tin NB; e) Tên người yêu cầu; f) Ngày nhận mẫu; g) Loại mẫu; h) Quy trình đo; i) Kết quả theo hệ SI; j) Khoảng tham chiếu; k) Diễn giải; l) Các nhận xét khác; m) Nhận biết người xem xét; n) Ngày ký duyệt; o) Số trang; p) Khoảng trống phiên giải.', evidence: 'Biểu mẫu: Phiếu tổng trả kết quả xét nghiệm (mã số XN-BM 5.8.10/01).' },
        { id: '8.22', name: 'PXN xây dựng quy trình trả kết quả XN trong đó nêu rõ người có thẩm quyền ban hành và người nhận kết quả, có bao gồm: a) Chỉ rõ nếu chất lượng mẫu không phù hợp; b) Thông báo kết quả "cảnh báo"; c) Kết quả rõ ràng, không lỗi sao chép; d) Báo cáo tạm thời; e) Trả kết quả đúng người; f) Báo cáo miệng được trả bằng văn bản sau đó; g) Có hồ sơ ghi chép kết quả báo miệng.', evidence: 'Quy trình trả kết quả xét nghiệm: Mã số XN-QTQL 5.8.10\n- Biểu mẫu: Phiếu tổng trả kết quả xét nghiệm (mã số XN-BM 5.8.10/01).\nBiểu mẫu: Sổ trả kết quả khoa phòng (mã số XN-BM 5.8.10/02).\nBiểu mẫu: Sổ trả kết quả qua điện thoại (mã số XN-BM 5.8.10/03).\nBiểu mẫu: Sổ trả kết quả cảnh báo (mã số XN-BM 5.8.10/04).' },
        { id: '8.23', name: 'PXN có quy định thực hiện việc sửa đổi kết quả xét nghiệm: a) Kết quả đã sửa được nhận biết rõ ràng; b) Khách hàng biết kết quả có sửa đổi; c) Hồ sơ sửa đổi có thể hiện thời gian, ngày và tên người chịu trách nhiệm.', evidence: 'Quy trình công bố kết quả xét nghiệm: Mã số XN-QTQL 5.8.11\n- Biểu mẫu: Sổ thu hồi kết quả (mã số XN-BM 5.8.11/01).' },
        { id: '8.24', name: 'Kết quả ban đầu được lưu giữ khi thực hiện các sửa đổi.', evidence: 'Lưu giữ lại các kết quả gốc ban đầu khi có sửa đổi kết quả.' },
        { id: '8.25', name: 'PXN có quy trình nhận dạng, thu thập, lưu trữ, đánh số, tiếp cận, bảo quản, và tiêu hủy mẫu sau XN an toàn', evidence: 'Quy trình Lưu và hủy mẫu: Mã số XN-QTQL 5.8.9' },
        { id: '8.26', name: 'PXN lưu mẫu XN sau khi đã xét nghiệm theo đúng quy định', evidence: 'Biểu mẫu: Sổ lưu và hủy bệnh phẩm (mã số XN-BM 5.8.9/01).' },
        { id: '8.27', name: 'PXN thực hiện tiêu hủy bệnh phẩm theo đúng quy định', evidence: 'Biểu mẫu: Sổ lưu và hủy bệnh phẩm (mã số XN-BM 5.8.9/01).' },
    ]
  },
  {
    id: 'IX',
    title: 'Chương IX. Quản lý thông tin',
    criteriaCount: 6,
    maxScore: 11,
    criteria: [
        { id: '9.1', name: 'PXN có quy định, thực hiện bảo mật thông tin, kết quả xét nghiệm của khách hàng', evidence: 'Quy trình bảo mật thông tin khách hàng: Mã số XN-QTQL 5.9.2' },
        { id: '9.2', name: 'PXN xác định thẩm quyền và trách nhiệm của nhân viên, cụ thể những người: a) Truy cập dữ liệu và thông tin khách hàng; b) Nhập dữ liệu và kết quả xét nghiệm; c) Thay đổi dữ liệu hoặc kết quả xét nghiệm; d) Thẩm quyền ban hành kết quả và báo cáo xét nghiệm.', evidence: 'Quy trình Quản lý thông tin: Mã số XN-QTQL 5.9.1\n- Biểu mẫu: Danh sách cán bộ truy cập phần mềm (mã số XN-BM 5.9.1/03).' },
        { id: '9.3', name: 'Hệ thống thông tin điện tử được bảo vệ để ngăn ngừa việc truy cập trái phép', evidence: 'Quy trình Quản lý thông tin: Mã số XN-QTQL 5.9.1' },
        { id: '9.4', name: 'Hệ thống được duy trì đảm bảo tính toàn vẹn của dữ liệu và thông tin', evidence: 'Quy trình Quản lý thông tin: Mã số XN-QTQL 5.9.1\nBiểu mẫu: Phiếu kiểm tra sao lưu (mã số XN-BM 5.9.1/02).' },
        { id: '9.5', name: 'Lưu hồ sơ ghi nhận những lần hệ thống trục trặc, các hành động tức thì và khắc phục phù hợp', evidence: 'Biểu mẫu: Sổ theo dõi sự cố thông tin (mã số XN-BM 5.9.1/05).\n- Biểu mẫu: Phiếu báo cáo sự không phù hợp (mã số XN-BM 5.10.1/02).\nBiểu mẫu: Phiếu báo cáo hành động khắc phục (mã số XN-BM 5.11.1/02).' },
        { id: '9.6', name: 'PXN có kế hoạch dự phòng trong trường hợp hệ thống quản lý thông tin điện tử bị hỏng hoặc khi bảo trì', evidence: 'Quy trình Quản lý thông tin: Mã số XN-QTQL 5.9.1' },
    ]
  },
  {
    id: 'X',
    title: 'Chương X. Xác định sự không phù hợp, hành động khắc phục và hành động phòng ngừa',
    criteriaCount: 6,
    maxScore: 14,
    criteria: [
        { id: '10.1', name: 'PXN có quy định bằng văn bản việc nhận biết và kiểm soát SKPH; Văn bản bao gồm những điểm sau: a) Xác định các loại SKPH; b) Lưu giữ thông tin về SKPH; c) Trách nhiệm và thẩm quyền xử lý; d) Hành động tức thì; e) Xác định mức độ ảnh hưởng; f) Tạm dừng XN và thu hồi KQ; g) Thông báo cho BS; h) Thu hồi KQ được nhận biết; i) Ghi lại hồ sơ; j) Xác định thời gian giải quyết; k) Đảm bảo thu hồi KQ; l) Trả KQ sau khi khắc phục.', evidence: 'Quy trình Kiểm soát sự không phù hợp: Mã số XN-QTQL 5.10.1' },
        { id: '10.2', name: 'Hồ sơ sự không phù hợp có được ghi chép đầy đủ và lưu trữ thích hợp theo quy định của PXN', evidence: 'Biểu mẫu: Sổ theo dõi sự sự không phù hợp (mã số XN-BM 5.10.1/01).\nBiểu mẫu: Phiếu báo cáo sự không phù hợp (mã số XN-BM 5.10.1/02).' },
        { id: '10.3', name: 'PXN có quy định bằng văn bản việc thực hiện hành động khắc phục bao gồm các vấn đề sau: a) Xác định nguyên nhân gốc rễ; b) Thực hiện HĐKP; c) Ghi lại kết quả; d) Xem xét và đánh giá hiệu quả; e) Đánh giá sự cần thiết thực hiện HĐPN.', evidence: 'Quy trình Hành động khắc phục: Mã số XN-QTQL 5.10.2' },
        { id: '10.4', name: 'Hồ sơ HĐKP được ghi chép đầy đủ và lưu trữ thích hợp theo quy định', evidence: 'Biểu mẫu: Sổ theo dõi hành động khắc phục (mã số XN-BM 5.10.2/01).\nBiểu mẫu: Phiếu báo cáo hành động khắc phục (mã số XN-BM 5.10.2/02).' },
        { id: '10.5', name: 'PXN có quy định bằng văn bản thực hiện HĐPN, bao gồm các nội dung sau: a) Xem xét dữ liệu để xác định SKPH tiềm tàng; b) Xác định nguyên nhân gốc rễ; c) Đánh giá sự cần thiết; d) Xác định và thực hiện; e) Ghi lại kết quả; j) Xem xét hiệu quả.', evidence: 'Quy trình Hành động phòng ngừa: Mã số XN-QTQL 5.10.3' },
        { id: '10.6', name: 'Hồ sơ các HĐPN có được ghi chép đầy đủ và lưu trữ thích hợp theo quy định của PXN; các HĐPN đã thực hiện có được xem xét và đánh giá hiệu quả, bao gồm: a) Xem xét số liệu và thông tin; b) Phân tích nguyên nhân gốc rễ; c) Thực hiện và lưu thông tin; d) Xem xét và đánh giá hiệu quả.', evidence: 'Biểu mẫu: Sổ theo dõi hành động phòng ngừa (mã số XN-BM 5.10.3/01).\nBiểu mẫu: Phiếu báo cáo hành động phòng ngừa (mã số XN-BM 5.10.3/02).' },
    ]
  },
  {
    id: 'XI',
    title: 'Chương XI. Cải tiến liên tục',
    criteriaCount: 8,
    maxScore: 21,
    criteria: [
        { id: '11.1', name: 'PXN có các quy định bằng văn bản về các bước thực hiện hoạt động cải tiến liên tục như sau: a) Xác định hoạt động; b) Xây dựng kế hoạch; c) Lưu trữ thông tin; d) Thực hiện kế hoạch; e) Trao đổi kế hoạch.', evidence: 'Quy trình Cải tiến liên tục: Mã số XN-QTQL 5.11.1' },
        { id: '11.2', name: 'PXN có xác định và thực hiện các hoạt động/dự án cải tiến liên tục', evidence: 'Biểu mẫu: Kế hoạch cải tiến chất lượng (mã số XN-BM 5.11.1/01).\nBiểu mẫu: Sổ theo dõi hoạt động cải tiến (mã số XN-BM 5.11.1/02).\nBiểu mẫu: Phiếu đề nghị và thực hiện cải tiến chất lượng (mã số XN-BM 5.11.1/03).' },
        { id: '11.3', name: 'PXN họp định kỳ do lãnh đạo cơ sở y tế hoặc đơn vị chủ trì để rà soát về việc áp dụng các chỉ số chất lượng, nhu cầu cải tiến liên tục.', evidence: 'Biểu mẫu: Chương trình xem xét của lãnh đạo (mã số: XN-BM 5.1.3/01)\nBiểu mẫu: Biên bản xem xét của lãnh đạo (mã số: XN-BM 5.1.3/02)' },
        { id: '11.4', name: 'Các chỉ số chất lượng có được theo dõi định kỳ', evidence: 'Biểu mẫu: Kế hoạch theo dõi chỉ số chất lượng (mã số: XN-BM 5.1.2/01).\n- Biểu mẫu: Phiếu báo cáo chỉ số chất lượng (mã số XN-BM 5.1.2/02).\nHồ sơ kết quả thống kê theo dõi từng chỉ số.' },
        { id: '11.5', name: 'Áp dụng các công cụ đồ họa (biểu đồ, đồ thị để trao đổi các phát hiện và xu hướng chất lượng (nếu có thể)', evidence: 'Biểu mẫu: Phiếu báo cáo chỉ số chất lượng (mã số XN-BM 5.1.2/02).' },
        { id: '11.6', name: 'Kết quả quá trình xem xét và phân tích chỉ số chất lượng được sử dụng để cải tiến chất lượng PXN', evidence: 'Biểu mẫu: Phiếu báo cáo chỉ số chất lượng (mã số XN-BM 5.1.2/02).\n– Biểu mẫu: Biên bản xem xét của lãnh đạo (mã số: XN-BM 5.1.3/02)' },
        { id: '11.7', name: 'Các hành động cải tiến liên tục được xem xét định kỳ và đánh giá nhằm xác định hiệu quả của chất lượng PXN', evidence: 'Biểu mẫu: Phiếu đề nghị và thực hiện cải tiến chất lượng (mã số XN-BM 5.11.1/03).\n- Biểu mẫu: Biên bản xem xét của lãnh đạo (mã số: XN-BM 5.1.3/02)' },
        { id: '11.8', name: 'Nhân viên PXN tham gia thực hiện các hoạt động cải tiến', evidence: 'Biểu mẫu: Biên bản họp nhân viên (mã số XN-BM 5.1.1/06).\nBiểu mẫu: Biên bản xem xét của lãnh đạo (mã số: XN-BM 5.1.3/02)\nBiểu mẫu: Kế hoạch cải tiến chất lượng (mã số XN-BM 5.11.1/01).' },
    ]
  },
  {
    id: 'XII',
    title: 'Chương XII. Cơ sở vật chất và an toàn',
    criteriaCount: 27,
    maxScore: 32,
    criteria: [
      { id: '12.1', name: 'PXN có đủ diện tích/không gian theo quy định và được phân chia thành các khu vực chức năng riêng biệt', evidence: 'Sơ đồ mặt bằng PXN' },
      { id: '12.2', name: 'Sổ tay an toàn cập nhật có sẵn tại PXN và dễ dàng tiếp cận được', evidence: 'Sổ tay an toàn – Mã số XN-STAT' },
      { id: '12.3', name: 'Sổ tay an toàn bao gồm các nội dung: a) Thông tin chung; b) Chính sách an toàn; c) Đánh giá nguy cơ; d) Quản lý an toàn; e) An toàn về máu và dịch; f) Xử lý chất thải; g) Hóa chất nguy hại; h) Bảng chỉ dẫn an toàn hóa chất (MSDS); i) Trang bị bảo hộ cá nhân; j) Tiêm phòng; k) Dự phòng sau phơi nhiễm; l) An toàn PCCC; m) An toàn điện.', evidence: 'Sổ tay an toàn – Mã số XN-STAT' },
      { id: '12.4', name: 'PXN có khu vực sinh hoạt cho nhân viên, bao gồm: a) Phòng vệ sinh; b) Nguồn nước uống; c) Khu vực thay đồ thông thường, hay bộ bảo hộ lao động cá nhân.', evidence: 'Sơ đồ mặt bằng PXN' },
      { id: '12.5', name: 'Có khu vực lấy mẫu bệnh phẩm riêng bao gồm: a) Khu vực lấy mẫu được trang bị phù hợp đảm bảo sự riêng tư, kín đáo và thoải mái cho khách hàng; b) Phòng vệ sinh; c) PXN có hộp sơ cấp cứu cho nhân viên và khách hàng tại khu vực lấy mẫu.', evidence: 'Sơ đồ mặt bằng PXN' },
      { id: '12.6', name: 'PXN có kiểm soát việc tiếp cận tới khu vực thực hiện xét nghiệm', evidence: 'Biểu mẫu: Quy định ra vào khu vực xét nghiệm (mã số XN-BM 5.12.1/01).\nBiểu mẫu: Nhật ký ra vào khu vực xét nghiệm (mã số XN-BM 5.12.1/02).' },
      { id: '12.7', name: 'PXN có được trang bị phù hợp cho việc thực hiện xét nghiệm, bao gồm: a) Nguồn điện dự phòng; b) Chiếu sáng; c) Thông gió; d) Kiểm soát tiếng ồn; e) Nước; f) Ghế ngồi thực hiện xét nghiệm có chiều cao phù hợp với loại xét nghiệm thực hiện; g) Xử lý chất thải đúng quy định.', evidence: 'Hồ sơ báo cáo môi trường' },
      { id: '12.8', name: 'PXN có trang bị bảo hộ lao động phù hợp và dễ dàng tiếp cận', evidence: 'Biểu mẫu: Danh sách bảo hộ cá nhân (mã số XN-BM 5.12.1/09).' },
      { id: '12.9', name: 'Các thiết bị an toàn được trang bị đầy đủ và kiểm tra chức năng định kỳ gồm: a) Tủ an toàn sinh học; b) Ly tâm có nắp đậy; c) Nơi rửa tay; d) Dụng cụ rửa mắt/ dung dịch rửa mắt thích hợp; e) Dụng cụ xử lí mẫu tràn, đổ; f) Bộ sơ cứu.', evidence: 'Biểu mẫu: Danh mục trang thiết bị (mã số XN-BM 5.5.1/01).\nBiểu mẫu: Kế hoạch hiệu chuẩn và bảo dưỡng thiết bị (mã số XN-BM 5.5.1/06).' },
      { id: '12.10', name: 'Quá trình khử nhiễm PXN được thực hiện thường xuyên và ghi chép lại', evidence: 'Biểu mẫu: Phiếu theo dõi khử nhiễm (mã số XN-BM 5.12.1/14).' },
      { id: '12.11', name: 'PXN có đủ không gian riêng để lưu trữ các vật liệu sau: a) Mẫu bệnh phẩm; b) Tài liệu và hồ sơ; c) Thiết bị; d) Sinh phẩm, hóa chất và vật tư.', evidence: 'Sơ đồ mặt bằng PXN' },
      { id: '12.12', name: 'Điều kiện của khu vực lưu trữ được kiểm soát và đảm bảo tránh nhiễm chéo', evidence: 'Biểu mẫu: Phiếu theo dõi điều kiện môi trường (mã số XN-BM 5.12.1/03).' },
      { id: '12.13', name: 'Mẫu bệnh phẩm được lưu trữ tách biệt với sinh phẩm, hóa chất và các sản phẩm huyết học.', evidence: 'Sắp xếp tủ lưu mẫu' },
      { id: '12.14', name: 'Các vật liệu nguy hiểm phải được lưu trữ, bảo quản, sử dụng bảo đảm an toàn theo quy định', evidence: 'Sắp xếp khu vực lưu' },
      { id: '12.15', name: 'Khu vực làm việc sạch sẽ và được duy trì thường xuyên, có các bảng cảnh báo phù hợp', evidence: 'Biểu mẫu: Các mẫu biển báo cửa phòng (mã số XN-BM 5.12.1/10).' },
      { id: '12.16', name: 'Dây điện, phích cắm, ổ cắm được bố trí hợp lý và thuận tiện.', evidence: 'Sơ đồ mặt bằng' },
      { id: '12.17', name: 'Có nguồn điện dự phòng bảo đảm cung cấp điện cho các TTB có thể ảnh hưởng đến kết quả xét nghiệm.', evidence: 'Biểu mẫu: Danh mục trang thiết bị (mã số XN-BM 5.5.1/01).' },
      { id: '12.18', name: 'Các TTB được đặt tại vị trí phù hợp (xa nguồn nước, xa khu vực để hóa chất độc hại...).', evidence: 'Sơ đồ mặt bằng' },
      { id: '12.19', name: 'Chất thải nhiễm khuẩn và không nhiễm khuẩn được tách riêng.', evidence: 'Biểu mẫu: Danh sách dụng cụ chứa chất thải (mã số XN-BM 5.12.1/08).' },
      { id: '12.20', name: 'Chất thải nhiễm khuẩn được xử lý theo đúng quy định như hấp, đốt.', evidence: 'Hợp đồng xử lý rác (nếu có)\nBiểu mẫu: Sổ bàn giao chất thải (mã số XN-BM 5.12.1/15).' },
      { id: '12.21', name: 'Các hóa chất nguy hiểm/vật liệu nguy hiểm được hủy bỏ /xử lí theo đúng quy định', evidence: 'Biểu mẫu: Sổ bàn giao chất thải (mã số XN-BM 5.12.1/15).' },
      { id: '12.22', name: 'Xử lý “vật sắc nhọn” và sử dụng hộp chứa “vật sắc nhọn” một cách hợp lý', evidence: 'Biểu mẫu: Danh sách dụng cụ chứa chất thải (mã số XN-BM 5.12.1/08).' },
      { id: '12.23', name: 'Chương trình an toàn của PXN bao gồm an toàn phòng cháy chữa cháy: a) PXN có sẵn bình cứu hỏa hoạt động được và thường xuyên được kiểm tra. b) PXN có hệ thống chuông báo cháy và diễn tập chữa cháy định kỳ.', evidence: 'Quy trình hưỡng dẫn an toàn – Mã số XN-QTQL 5.12.2\nBiểu mẫu: Biên bản kiểm tra an toàn (mã số XN-BM 5.12.2/02).\nBiểu mẫu: Sổ bàn giao chất thải (mã số XN-BM 5.12.1/15).' },
      { id: '12.24', name: 'PXN có kế hoạch và thực hiện kiểm tra an toàn định kỳ', evidence: 'Biểu mẫu: Kế hoạch kiểm tra an toàn (mã số XN-BM 5.12.2/01).\nBiểu mẫu: Biên bản kiểm tra an toàn (mã số XN-BM 5.12.2/02).' },
      { id: '12.25', name: 'Việc kiểm tra an toàn được người đã được tập huấn về ATSH thực hiện.', evidence: 'Biểu mẫu: Biên bản kiểm tra an toàn (mã số XN-BM 5.12.2/02).' },
      { id: '12.26', name: 'Các vấn đề phát hiện trong quá trình kiểm tra an toàn được lưu hồ sơ và báo cáo với người có trách nhiệm để xem xét.', evidence: 'Biểu mẫu: Biên bản kiểm tra an toàn (mã số XN-BM 5.12.2/02).\nBiểu mẫu: Phiếu báo cáo sự cố (mã số XN-BM 5.12.1/07).' },
      { id: '12.27', name: 'PXN phân công nhân viên an toàn để giám sát thực hiện chương trình an toàn trong PXN', evidence: 'Quyết định bổ nhiệm/phân công nhân viên an toàn\nBản mô tả công việc của nhân viên được phân công' },
    ]
  },
];
